# Generated by Django 4.2.28 on 2026-03-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_asignacioncurso_catedratico_curso_inscripcionalumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.AlterField(
            model_name='asignacioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Alumno.cursos'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
