# Generated by Django 4.2.28 on 2026-03-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0004_cursos_alter_asignacioncurso_curso_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
